version: "2.1"
services:
  db:
    image: arminc/clair-db:latest
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  clair:
    image: arminc/clair-local-scan:v2.0.5
    depends_on:
      db:
        condition: service_healthy
    links:
      - "db:postgres"
    ports:
      - "6060:6060"

  clair-scanner:
    image: kiseruio/clair-sec-scanner:1.0.0
    depends_on:
      - clair
    ports:
      - "9279:9279"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: clair-scanner --ip clair-scanner --clair=http://clair:6060 -t ${LEVEL:-Critical} -w ${WHITELIST:-/usr/local/default-whitelist.yaml } ${IMAGE}

